(()=>{(function(){var i,r,s,n,l=[];class t{static messages=[];static thinking=!1;static hasKey(){return Settings.get("ai_key")!=""}static sendRequest(a){let g={Authorization:"Bearer "+Buffer.from(localStorage.getItem("ai_bench_key"),"base64").toString("utf8"),"OpenAI-Organization":Buffer.from(localStorage.getItem("ai_bench_org"),"base64").toString("utf8"),"OpenAI-Project":Buffer.from(localStorage.getItem("ai_bench_proj"),"base64").toString("utf8"),"Content-Type":"application/json"},d={model:localStorage.getItem("ai_bench_model"),messages:[{role:"user",content:"How many sides does a cube have?"}]};fetch("https://api.openai.com/v1/chat/completions",{method:"POST",headers:g,body:JSON.stringify(d)}).then(o=>{if(!o.ok){o.json().then(c=>{console.warn(c),t.messages.push({role:"system",color:"#f01e2c",content:o.body.error?o.body.error:`Error ${o.status}: ${c.error.message}`})});return}t.messages.push({role:"system",content:o.body})})}static sendMessage(a){if(a.toLowerCase()=="/clear"){this.messages.empty();return}if(this.messages.push({role:"user",content:a}),!this.hasKey()){this.messages.push({role:"system",color:"#f01e2c",content:"Please provide an API key!"});return}this.sendRequest(a)}}BBPlugin.register("ai_bench",{title:"AI Bench",author:"legopitstop",description:"desc",icon:"icon.png",version:"1.0.0",variant:"both",new_repository_format:!0,tags:["Blockbench","ChatGPT","AI"],onload(){n=new Dialog("ai_config",{title:"OpenAI Config",form:{info:{type:"info",text:"This dialog contains your credentials for OpenAI"},key:{type:"password",label:"Key",value:""},proj:{type:"password",label:"Project",value:""},org:{type:"password",label:"Organization",value:""},model:{type:"select",label:"Model",value:localStorage.getItem("ai_bench_model")||"",options:{"gpt-4o":"GPT-4o","gpt-4o-mini":"GPT-4o mini","stable-diffusion-v1-5":"Stable Diffusion v1.5 (local)"}}},onConfirm(e){e.key&&localStorage.setItem("ai_bench_key",Buffer.from(e.key,"utf8").toString("base64")),e.org&&localStorage.setItem("ai_bench_org",Buffer.from(e.org,"utf8").toString("base64")),e.proj&&localStorage.setItem("ai_bench_proj",Buffer.from(e.proj,"utf8").toString("base64")),localStorage.setItem("ai_bench_model",e.model)}}),s=new Setting("ai_config",{type:"click",name:"OpenAI Config",description:"Your credentials for OpenAI.",category:"application",icon:"auto_awesome",click(){n.show()}}),i=new Panel("ai_bench",{icon:"auto_awesome",name:"AI Bench",default_position:{slot:"right_bar",float_position:[0,0],float_size:[400,300],height:300,folded:!1},growable:!0,resizable:!0,condition:{method(){return navigator.onLine}},component:{name:"panel-ai",data(){return{messages:t.messages,thinking:t.thinking,content:""}},methods:{getUsername(e){return e=="user"?Settings.get("username"):"Bench"},sendMessage(){this.content&&(t.sendMessage(this.content),this.content="")}},template:`
          <div>
            <ul id="ai_history">
              <li v-for="msg in messages">
                <b :class="msg.role" v-if="msg.color == undefined">{{ getUsername(msg.role) }}:</b>
                <span class="text" :style="'color:' + (msg.color === undefined ? 'inherit' : msg.color) + ';'">{{ msg.content }}</span>
              </li>
            </ul>
            <div id="ai_chat_bar">
              <input type="text" id="ai_chat_input" maxlength="512" class="dark_bordered f_left" v-model="content" @keyup.enter="sendMessage" :disabled="thinking">
              <i class="material-icons" @click="sendMessage">send</i>
            </div>
          </div>
          `}}),r=Blockbench.addCSS(`#ai_history{background:var(--color-back);color:var(--color-text);padding:5px;font-size:12pt;overflow-y:scroll;overflow-x:hidden;word-break:break-word;min-height:81px;}
        #ai_history li{padding-top:1px;padding-left:7px;clear:both;}
        #ai_history li b.user{color:var(--color-accent_text);background-color:var(--color-accent);}
        #ai_history li b{margin-left:-6px;border-radius:4px;padding:1px 4px;background-color:var(--color-button);}
        #ai_chat_bar{height:32px;margin-bottom:6px;margin-top:5px;}
        #ai_chat_input{padding:5px;width:calc(100% - 36px);margin-left:2px;}
        `),l.push(i,r,s,n)},onuninstall(){localStorage.removeItem("ai_bench_key"),localStorage.removeItem("ai_bench_proj"),localStorage.removeItem("ai_bench_org")},onunload(){l.forEach(e=>e.delete())}})})();})();
